# Generated by Django 4.2.16 on 2024-11-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='mount_state',
            field=models.CharField(choices=[('automatic', 'Automatique'), ('live', 'En direct')], default='live', max_length=50, verbose_name='État du Mount'),
        ),
    ]
